<?php
    echo"<br>";
    $ar1=["a","b","c","d","e"];
    print_r($ar1);
    echo"<br>\$ar2:<br>";
    $ar2=array_slice($ar1,1,2);
    print_r($ar2);
    echo"<br>\$ar<br>";
    $ar3=array_slice($ar1,1,2,true);
    print_r($ar3);
?>